import json
import requests
from typing import Dict, Any, Generator, List, Optional
from legal_ai.config import OLLAMA_BASE_URL, OLLAMA_LLM_MODEL

class LocalOllamaClient:
    def __init__(self):
        self.base_url = OLLAMA_BASE_URL.rstrip('/')
        self.model = OLLAMA_LLM_MODEL

    def generate(
        self, 
        prompt: str, 
        system_prompt: Optional[str] = None, 
        json_format: bool = False,
        temperature: float = 0.2,
        model_override: Optional[str] = None
    ) -> str:
        """
        Queries the local Ollama instance for text generation.
        """
        url = f"{self.base_url}/api/generate"
        
        options = {
            "temperature": temperature
        }
        
        target_model = model_override if model_override else self.model
        
        payload = {
            "model": target_model,
            "prompt": prompt,
            "stream": False,
            "options": options
        }
        
        if system_prompt:
            payload["system"] = system_prompt
        if json_format:
            payload["format"] = "json"
            
        try:
            response = requests.post(url, json=payload, timeout=120)
            response.raise_for_status()
            response_json = response.json()
            return response_json.get("response", "")
        except requests.exceptions.RequestException as e:
            print(f"[!] Ollama request failed: {e}")
            raise RuntimeError(f"Ollama connection error. Verify Ollama is running at {self.base_url} and model '{target_model}' is loaded.")

    def chat_stream(
        self, 
        messages: List[Dict[str, str]], 
        temperature: float = 0.2,
        model_override: Optional[str] = None
    ) -> Generator[str, None, None]:
        """
        Initiates a streaming chat session with the local Ollama instance.
        Yields tokens as they are generated by the model.
        """
        url = f"{self.base_url}/api/chat"
        target_model = model_override if model_override else self.model
        
        payload = {
            "model": target_model,
            "messages": messages,
            "stream": True,
            "options": {
                "temperature": temperature
            }
        }
        
        try:
            # We use stream=True on requests to yield chunks line-by-line
            response = requests.post(url, json=payload, stream=True, timeout=120)
            response.raise_for_status()
            
            for line in response.iter_lines():
                if line:
                    chunk = json.loads(line.decode("utf-8"))
                    message_content = chunk.get("message", {}).get("content", "")
                    if message_content:
                        yield message_content
                        
        except requests.exceptions.RequestException as e:
            print(f"[!] Ollama chat stream connection failed: {e}")
            raise RuntimeError(f"Ollama connection error during streaming: {e}")
