"""add statutory mappings

Revision ID: 137b7ec3d32e
Revises: 9aad84c4b2a2
Create Date: 2026-06-29 13:14:36.546788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137b7ec3d32e'
down_revision: Union[str, Sequence[str], None] = '9aad84c4b2a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statutory_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_act', sa.String(), nullable=False),
    sa.Column('old_section', sa.String(), nullable=False),
    sa.Column('new_act', sa.String(), nullable=False),
    sa.Column('new_section', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('change_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statutory_mappings_id'), 'statutory_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_statutory_mappings_new_act'), 'statutory_mappings', ['new_act'], unique=False)
    op.create_index(op.f('ix_statutory_mappings_new_section'), 'statutory_mappings', ['new_section'], unique=False)
    op.create_index(op.f('ix_statutory_mappings_old_act'), 'statutory_mappings', ['old_act'], unique=False)
    op.create_index(op.f('ix_statutory_mappings_old_section'), 'statutory_mappings', ['old_section'], unique=False)
    op.create_index(op.f('ix_annotations_document_id'), 'annotations', ['document_id'], unique=False)
    op.create_index(op.f('ix_documents_matter_id'), 'documents', ['matter_id'], unique=False)
    op.create_index(op.f('ix_invoices_client_id'), 'invoices', ['client_id'], unique=False)
    op.create_index(op.f('ix_invoices_matter_id'), 'invoices', ['matter_id'], unique=False)
    op.create_index(op.f('ix_matters_client_id'), 'matters', ['client_id'], unique=False)
    op.create_index(op.f('ix_schedules_matter_id'), 'schedules', ['matter_id'], unique=False)
    op.create_index(op.f('ix_time_entries_matter_id'), 'time_entries', ['matter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_entries_matter_id'), table_name='time_entries')
    op.drop_index(op.f('ix_schedules_matter_id'), table_name='schedules')
    op.drop_index(op.f('ix_matters_client_id'), table_name='matters')
    op.drop_index(op.f('ix_invoices_matter_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_client_id'), table_name='invoices')
    op.drop_index(op.f('ix_documents_matter_id'), table_name='documents')
    op.drop_index(op.f('ix_annotations_document_id'), table_name='annotations')
    op.drop_index(op.f('ix_statutory_mappings_old_section'), table_name='statutory_mappings')
    op.drop_index(op.f('ix_statutory_mappings_old_act'), table_name='statutory_mappings')
    op.drop_index(op.f('ix_statutory_mappings_new_section'), table_name='statutory_mappings')
    op.drop_index(op.f('ix_statutory_mappings_new_act'), table_name='statutory_mappings')
    op.drop_index(op.f('ix_statutory_mappings_id'), table_name='statutory_mappings')
    op.drop_table('statutory_mappings')
    # ### end Alembic commands ###
