"""Initial migration

Revision ID: bca1aa2b554f
Revises: 
Create Date: 2026-06-25 11:29:20.305625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bca1aa2b554f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ux_matters_case_number_notnull'), table_name='matters', sqlite_where=sa.text('case_number IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ux_matters_case_number_notnull'), 'matters', ['case_number'], unique=1, sqlite_where=sa.text('case_number IS NOT NULL'))
    # ### end Alembic commands ###
